MathsLibrary: Matrix< T, ROWS, COLS > Class Template Reference
Matrix< T, ROWS, COLS > Class Template Reference
Creates matrices and vectors using a template type, number of rows and numbers of columns and applies a variety of operations and functions to them.
#include <matrix.h>
Public Member Functions
Matrix ()
Default constructor, sets all values of m_data equil to zero, also determnines if the cretaed matrix is a vector or not.
Matrix (std::initializer_list< T > data)
Initializer list constructor, allows user to construct a matrix or vector using an initializer list to assign its values Borrowed from Jon Macey code from Array.h Modified from :- Jon Macey (January 5th, 2017). Array.h [online]. [Accessed Jan 2017]. Available from: "http://www.github.com/".
Matrix (const Matrix< T, ROWS, COLS > &_rhs)
Copy constructor.
const int * rows () const
int getRows ()
const int * cols () const
int getCols ()
const T * data (int _row, int _col) const
T data (int _row, int _col)
T & operator() (std::size_t _rowID, std::size_t _colID)
Subscript operator used to view values of matrix/vector based on row and column, starts at 1 not zero, eg first value is (1,1) param[in] _rowID, the row of the data you would like to access (1 for first row). param[in] _colID, the column of the data you would like to access (1 for first column).
const T & operator() (std::size_t _rowID, std::size_t _colID) const
Subscript operator used to view values of matrix/vector based on row and column (read only) param[in] _rowID, the row of the data you would like to view (1 for first row). param[in] _colID, the column of the data you would like to view (1 for first column).
template<size_t N, size_t M>
Matrix< T, ROWS, COLS > operator= (Matrix< T, N, M > &_rhs)
Matrix and Vector Operation.
Matrix & operator= (const Matrix< T, ROWS, COLS > &_rhs)
Asignment Operator param[in] _rhs, the matrix or vector that the first matrix or vector will be assigned too.
Matrix & operator+ (const Matrix< T, ROWS, COLS > &_rhs)
Addition operator for matrix/vector and matrix/vector addition param[in] _rhs, the vector or matrix that is added to the first vector or matrix.
Matrix & operator- (const Matrix< T, ROWS, COLS > &_rhs)
Subtraction operator for matrix/vector and matrix/vector subtraction param[in] _rhs, the vector or matrix that is subtracted from the first vector or matrix.
bool operator== (const Matrix< T, ROWS, COLS > &_rhs)
Equility Operator, tests if vectors or matrices are equil and returns true if they are param[in] _rhs, the matrix or vector to test that the first vector or matrix equils.
Matrix & operator- ()
Negative operator, returns each value of the matrix or vector with the opposite sign.
Matrix & operator+ (T _scalar)
Addition operator for matrix/vector addition by a scalar amount param[in] _scalar, amount to add to each value of m_data for the given matrix/vector.
Matrix & operator- (T _scalar)
Subtraction operator for matrix/vector subtration by a scalar amount param[in] _scalar, amount to subtract from each value of m_data for the given matrix/vector.
Matrix & operator* (T _scalar)
Multiplication opertor for matrix/vector and _scalar param[in] _scalar, the value to multiple each value of m_data of the given matrix/vector by.
Matrix & operator/ (T _scalar)
Division operator for matrix/vector and _scalar param[in] _scalar, the value to divide each value of m_data of the given matrix/vector by.
template<size_t N>
Matrix< T, ROWS, COLS > & operator* (Matrix< T, COLS, N > &_rhs)
Matrix only operations.
Matrix & inverse ()
Returns the inverse of a square matrix, must be a 2d,3d or 4d matrix. 3X3 matrix inverse code modified from ForgotCode. [Accessed 2017]. Available from: "http://forgetcode.com/C/1781-Inverse-Matrix-of-3x3" 4x4 matrix inverse code modified from StackOverFlow. [Accessed 2017]. Available from: "http://stackoverflow.com/questions/1148309/inverting-a-4x4-matrix".
T determinant ()
Returns the determinant of a squre matrix, must be a 2d,3d or 4d vector.
Matrix & minorMatrix (int _row, int _col)
finds the minor matrix of a matrix param[in] _row, the row to be excluded from the original matrix in order to find the minor matrix param[in] _col, the column to be excluded from the original matrix in order to find the minor matrix
Matrix & transpose ()
returns the transpose version of a matrix
bool orthogonal ()
Tests if the matrix is orthogonal (if the inversed matrix equils the transposed matrix)
float magnitude ()
Vector only methods.
Matrix & operator/ (Matrix< T, ROWS, COLS > &_rhs)
Division operator for vector and vector param[in] _rhs, the vector that the will be used to divide the other vector by.
float dot (Matrix< T, ROWS, COLS > &_rhs)
The dot product of the given vector and another vector passed in as a parameter param[in] _rhs, the second vector that will be used to find the dot product.
float angle (Matrix< T, ROWS, COLS > &_rhs)
Returns the angle between two vectors param[in] _rhs, the angle is found between the applied to vector and this vector.
Matrix & cross (Matrix< T, ROWS, COLS > &_rhs)
Finds the cross product of two vectors param[in] the second vector that is used to find the cross product.
Matrix & rotateVector (T _angle, const char *_axis)
Rotates a 2d or 3d column vector by an angle counter clockwise around the selected axis (if 3d). param[in] _angle, the angle to rotate the vector by. param[in] _axis, the axis to rotate the vector around.
Matrix & normalizeVector ()
Returns the normalized vector.
void resize (int _rows, int _cols)
Resizes a matrix, resulting matrix must have the same number of elements as original matrix. param[in] _rows, the number of rows of the resulting matrix param[in] _cols, the number of columns of the resulting matrix.
void print ()
Prints out the elements of the vector or matrix in the correct format.
Private Member Functions
void rangeCheck (std::size_t rowID, std::size_t _colID)
Checks rows and columns are in correct range, eg if you want the first row you would write 1 opposed to 0. param[in] _rowID, the row you would like to check is within 0 and the number of rows. param[in] _colID, the column you would like to check is within 0 and the number of columns.
void vectorCheck ()
Checks that function is being applied to a matrix not a vector, throws error if it is a vector.
Private Attributes
int m_rows =ROWS
int m_cols =COLS
T m_data [ROWS][COLS]
bool m_vector = false
Detailed Description
template<typename T, size_t ROWS = 0, size_t COLS = 0>
class Matrix< T, ROWS, COLS >
Creates matrices and vectors using a template type, number of rows and numbers of columns and applies a variety of operations and functions to them.
Author
Kate Edge
Version
1.0
Date
15/3/17
Definition at line 19 of file matrix.h.
Constructor & Destructor Documentation
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS >::Matrix ()
Default constructor, sets all values of m_data equil to zero, also determnines if the cretaed matrix is a vector or not.
Definition at line 150 of file matrix.h.
 {
   for (int r=0; r < ROWS; ++r)
   {
     for (int c=0; c < COLS; ++c)
     {
       m_data[r][c]=0;
     }
   }
   if(ROWS==1 || COLS==1)
   {
     m_vector=true;
   }
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS >::Matrix (std::initializer_list< T > data)
Initializer list constructor, allows user to construct a matrix or vector using an initializer list to assign its values Borrowed from Jon Macey code from Array.h Modified from :- Jon Macey (January 5th, 2017). Array.h [online]. [Accessed Jan 2017]. Available from: "http://www.github.com/".
Definition at line 188 of file matrix.h.
 {
   // throws error if too many values in initializer list, if too few the remaining vaules remain equil to 0
   if(data.size()>ROWS*COLS)
   {
     throw std::out_of_range("Too many elements initialized");
   }
   // copies the initializer lists data to m_data
   std::copy(data.begin(),data.end(),&m_data[0][0]);
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS >::Matrix (const Matrix< T, ROWS, COLS > & _rhs)
Copy constructor.
Definition at line 169 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_data.
 {
   for(int i=0; i<m_rows; i++)
   {
     for(int j=0; j<m_cols; j++)
     {
       m_data[i][j]=_rhs.m_data[i][j];
     }
   }
 }
Member Function Documentation
template<typename T , size_t ROWS, size_t COLS> float Matrix< T, ROWS, COLS >::angle (Matrix< T, ROWS, COLS > & _rhs)
Returns the angle between two vectors param[in] _rhs, the angle is found between the applied to vector and this vector.
Definition at line 620 of file matrix.h.
References Matrix< T, ROWS, COLS >::magnitude(), and Matrix< T, ROWS, COLS >::vectorCheck().
 {
   vectorCheck();
   _rhs.vectorCheck();
   float angle = 0;
   float cosAngle = 0;
   float dotProd = 0;
   float mag1;
   float mag2;
   // calculate angles of each vector
   mag1=magnitude();
   mag2=_rhs.magnitude();
   // calculate dot product of vectors
   dotProd= dot(_rhs);
   // calculate cos angle
   cosAngle=dotProd / (mag1 * mag2);
   // calculate angle then change from radians to degrees
   angle = (180/M_PI)*acos(cosAngle);
   return angle;
 }
template<typename T, size_t ROWS = 0, size_t COLS = 0> const int* Matrix< T, ROWS, COLS >::cols () const inline
Definition at line 58 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_cols.
 { return m_cols; }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::cross (Matrix< T, ROWS, COLS > & _rhs)
Finds the cross product of two vectors param[in] the second vector that is used to find the cross product.
Definition at line 653 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_data, and Matrix< T, ROWS, COLS >::vectorCheck().
 {
   if( ROWS*COLS != 3)
   {
     throw std::out_of_range("You must use a 3D vector for the cross product function");
   }
   vectorCheck();
   _rhs.vectorCheck();
   T tmp[ROWS][COLS];
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       tmp[i][j]=0;
     }
   }
   // col vector
   if(m_rows==1)
   {
     tmp[0][0]= m_data[0][1]*_rhs.m_data[0][2] - m_data[0][2]*_rhs.m_data[0][1];
     tmp[0][1]= m_data[0][2]*_rhs.m_data[0][0] - m_data[0][0]*_rhs.m_data[0][2];
     tmp[0][2]= m_data[0][0]*_rhs.m_data[0][1] - m_data[0][1]*_rhs.m_data[0][0];
     // assignning the tmp matrix's values to m_data
     for(int i=0; i<COLS; i++)
     {
       m_data[0][i]=tmp[0][i];
     }
   }
   // row vector
   else if(m_cols==1)
   {
     tmp[0][0]= m_data[1][0]*_rhs.m_data[2][0] - m_data[2][0]*_rhs.m_data[1][0];
     tmp[1][0]= m_data[2][0]*_rhs.m_data[0][0] - m_data[0][0]*_rhs.m_data[2][0];
     tmp[2][0]= m_data[0][0]*_rhs.m_data[1][0] - m_data[1][0]*_rhs.m_data[0][0];
     // assignning the tmp matrix's values to m_data
     for(int i=0; i<ROWS; i++)
     {
       m_data[0][i]=tmp[0][i];
     }
   }
   return *this;
 }
template<typename T, size_t ROWS = 0, size_t COLS = 0> const T* Matrix< T, ROWS, COLS >::data (int _row, int _col) const inline
Definition at line 63 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_data.
 { return m_data[_row][_col]; }
template<typename T, size_t ROWS = 0, size_t COLS = 0> T Matrix< T, ROWS, COLS >::data (int _row, int _col) inline
Definition at line 65 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_data.
 { return m_data[_row][_col]; }
template<typename T , size_t ROWS, size_t COLS> T Matrix< T, ROWS, COLS >::determinant ()
Returns the determinant of a squre matrix, must be a 2d,3d or 4d vector.
Definition at line 774 of file matrix.h.
 {
   // test to see if matrix times inverse equils identity
   if( ROWS != COLS)
   {
     throw std::out_of_range("You must use a square matrix for the inverse function");
   }
   T determinant = 0;
   if(ROWS==2)
   {
     determinant = (m_data[0][0]*m_data[1][1])-(m_data[0][1]*m_data[1][0]);
   }
   else if(ROWS==3)
   {
     for(int i=0;i<3;i++)
     {
      determinant = determinant + (m_data[0][i]*(m_data[1][(i+1)%3]*m_data[2][(i+2)%3] - m_data[1][(i+2)%3]*m_data[2][(i+1)%3]));
     }
   }
   else if(ROWS==4)
   {
     T inv[4][4];
     inv[0][0] = m_data[1][1] * m_data[2][2] * m_data[3][3] -
                 m_data[1][1] * m_data[2][3] * m_data[3][2] -
                 m_data[2][1] * m_data[1][2] * m_data[3][3] +
                 m_data[2][1] * m_data[1][3] * m_data[3][2] +
                 m_data[3][1] * m_data[1][2] * m_data[2][3] -
                 m_data[3][1] * m_data[1][3] * m_data[2][2];
     inv[1][0] = -m_data[1][0] * m_data[2][2] * m_data[3][3] +
                  m_data[1][0] * m_data[2][3] * m_data[3][2] +
                  m_data[2][0] * m_data[1][2] * m_data[3][3] -
                  m_data[2][0] * m_data[1][3] * m_data[3][2] -
                  m_data[3][0] * m_data[1][2] * m_data[2][3] +
                  m_data[3][0] * m_data[1][3] * m_data[2][2];
     inv[2][0] =  m_data[1][0] * m_data[2][1] * m_data[3][3] -
                  m_data[1][0] * m_data[2][3] * m_data[3][1] -
                  m_data[2][0] * m_data[1][1] * m_data[3][3] +
                  m_data[2][0] * m_data[1][3] * m_data[3][1] +
                  m_data[3][0] * m_data[1][1] * m_data[2][3] -
                  m_data[3][0] * m_data[1][3] * m_data[2][1];
     inv[3][0] = -m_data[1][0] * m_data[2][1] * m_data[3][2] +
                  m_data[1][0] * m_data[2][2] * m_data[3][1] +
                  m_data[2][0] * m_data[1][1] * m_data[3][2] -
                  m_data[2][0] * m_data[1][2] * m_data[3][1] -
                  m_data[3][0] * m_data[1][1] * m_data[2][2] +
                  m_data[3][0] * m_data[1][2] * m_data[2][1];
     determinant = m_data[0][0] * inv[0][0] + m_data[0][1] * inv[1][0] + m_data[0][2] * inv[2][0] + m_data[0][3] * inv[3][0];
   }
   return determinant;
 }
template<typename T , size_t ROWS, size_t COLS> float Matrix< T, ROWS, COLS >::dot (Matrix< T, ROWS, COLS > & _rhs)
The dot product of the given vector and another vector passed in as a parameter param[in] _rhs, the second vector that will be used to find the dot product.
Definition at line 589 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_data, and Matrix< T, ROWS, COLS >::vectorCheck().
 {
   vectorCheck();
   _rhs.vectorCheck();
   float dotProd = 0;
   if(m_rows == 1)
   {
     for(int i = 0; i<COLS; i++)
     {
       dotProd+=m_data[0][i]*_rhs.m_data[0][i];
     }
   }
   else if(m_cols == 1)
   {
     for(int i = 0; i<COLS; i++)
     {
       dotProd+=m_data[i][0]*_rhs.m_data[i][0];
     }
   }
   return dotProd;
 }
template<typename T, size_t ROWS = 0, size_t COLS = 0> int Matrix< T, ROWS, COLS >::getCols () inline
Definition at line 60 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_cols.
 {return m_cols;}
template<typename T, size_t ROWS = 0, size_t COLS = 0> int Matrix< T, ROWS, COLS >::getRows () inline
Definition at line 56 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_rows.
 {return m_rows;}
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::inverse ()
Returns the inverse of a square matrix, must be a 2d,3d or 4d matrix. 3X3 matrix inverse code modified from ForgotCode. [Accessed 2017]. Available from: "http://forgetcode.com/C/1781-Inverse-Matrix-of-3x3" 4x4 matrix inverse code modified from StackOverFlow. [Accessed 2017]. Available from: "http://stackoverflow.com/questions/1148309/inverting-a-4x4-matrix".
referenced from http://forgetcode.com/C/1781-Inverse-Matrix-of-3x3
Definition at line 845 of file matrix.h.
 {
   // test to see if matrix times inverse equils identity
   if( ROWS != COLS)
   {
    throw std::out_of_range("You must use a square matrix for the inverse function");
   }
   if( determinant()==0)
   {
     throw std::out_of_range("An inverse doesnt exist, the determinant is 0");
   }
   T tmp[ROWS][COLS];
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       tmp[i][j]=0;
     }
   }
   // find inverse of 2x2 matrix
   if(ROWS==2)
   {
     tmp[0][0]= m_data[1][1];
     tmp[0][1]=-m_data[0][1];
     tmp[1][0]=-m_data[1][0];
     tmp[1][1]= m_data[0][0];
     for(int i = 0; i<ROWS; i++)
     {
       for( int j = 0; j<COLS; j++)
       {
         tmp[i][j]=tmp[i][j]/determinant();
       }
     }
   }
   if(ROWS==3)
   {
     for(int i=0;i<3;i++)
     {
       for(int j=0;j<3;j++)
       {
         tmp[j][i] = ((m_data[(i+1)%3][(j+1)%3] * m_data[(i+2)%3][(j+2)%3]) -
                     (m_data[(i+1)%3][(j+2)%3]*m_data[(i+2)%3][(j+1)%3]))/ determinant();
       }
     }
   }
   // referenced from http://stackoverflow.com/questions/1148309/inverting-a-4x4-matrix
   // 4x4 matrix
   if(ROWS==4)
   {
     T inv[4][4];
     T det = 0;
     // initilize inv matrix values to zero
     for(int i = 0; i<ROWS; i++)
     {
       for( int j = 0; j<COLS; j++)
       {
         inv[i][j]=0;
       }
     }
     inv[0][0] = m_data[1][1] * m_data[2][2] * m_data[3][3] -
                 m_data[1][1] * m_data[2][3] * m_data[3][2] -
                 m_data[2][1] * m_data[1][2] * m_data[3][3] +
                 m_data[2][1] * m_data[1][3] * m_data[3][2] +
                 m_data[3][1] * m_data[1][2] * m_data[2][3] -
                 m_data[3][1] * m_data[1][3] * m_data[2][2];
     inv[1][0] = -m_data[1][0]  * m_data[2][2] * m_data[3][3] + //4
                  m_data[1][0]  * m_data[2][3] * m_data[3][2] +
                  m_data[2][0]  * m_data[1][2]  * m_data[3][3] -
                  m_data[2][0]  * m_data[1][3]  * m_data[3][2] -
                  m_data[3][0] * m_data[1][2]  * m_data[2][3] +
                  m_data[3][0] * m_data[1][3]  * m_data[2][2];
     inv[2][0] = m_data[1][0]  * m_data[2][1] * m_data[3][3] - //8
                 m_data[1][0]  * m_data[2][3] * m_data[3][1] -
                 m_data[2][0]  * m_data[1][1] * m_data[3][3] +
                 m_data[2][0]  * m_data[1][3] * m_data[3][1] +
                 m_data[3][0] * m_data[1][1] * m_data[2][3] -
                 m_data[3][0] * m_data[1][3] * m_data[2][1];
     inv[3][0] = -m_data[1][0]  * m_data[2][1] * m_data[3][2] + //12
                  m_data[1][0]  * m_data[2][2] * m_data[3][1] +
                  m_data[2][0]  * m_data[1][1] * m_data[3][2] -
                  m_data[2][0]  * m_data[1][2] * m_data[3][1] -
                  m_data[3][0] * m_data[1][1] * m_data[2][2] +
                  m_data[3][0] * m_data[1][2] * m_data[2][1];
     inv[0][1] = -m_data[0][1]  * m_data[2][2] * m_data[3][3] + //1
                  m_data[0][1]  * m_data[2][3] * m_data[3][2] +
                  m_data[2][1]  * m_data[0][2] * m_data[3][3] -
                  m_data[2][1]  * m_data[0][3] * m_data[3][2] -
                  m_data[3][1] * m_data[0][2] * m_data[2][3] +
                  m_data[3][1] * m_data[0][3] * m_data[2][2];
     inv[1][1] = m_data[0][0]  * m_data[2][2] * m_data[3][3] - //5
                 m_data[0][0]  * m_data[2][3] * m_data[3][2] -
                 m_data[2][0]  * m_data[0][2] * m_data[3][3] +
                 m_data[2][0]  * m_data[0][3] * m_data[3][2] +
                 m_data[3][0] * m_data[0][2] * m_data[2][3] -
                 m_data[3][0] * m_data[0][3] * m_data[2][2];
     inv[2][1] = -m_data[0][0]  * m_data[2][1] * m_data[3][3] + //9
                  m_data[0][0]  * m_data[2][3] * m_data[3][1] +
                  m_data[2][0]  * m_data[0][1] * m_data[3][3] -
                  m_data[2][0]  * m_data[0][3] * m_data[3][1] -
                  m_data[3][0] * m_data[0][1] * m_data[2][3] +
                  m_data[3][0] * m_data[0][3] * m_data[2][1];
     inv[3][1] = m_data[0][0]  * m_data[2][1] * m_data[3][2] - //13
                 m_data[0][0]  * m_data[2][2] * m_data[3][1] -
                 m_data[2][0]  * m_data[0][1] * m_data[3][2] +
                 m_data[2][0]  * m_data[0][2] * m_data[3][1] +
                 m_data[3][0] * m_data[0][1] * m_data[2][2] -
                 m_data[3][0] * m_data[0][2] * m_data[2][1];
     inv[0][2] = m_data[0][1]  * m_data[1][2] * m_data[3][3] - //2
                 m_data[0][1]  * m_data[1][3] * m_data[3][2] -
                 m_data[1][1]  * m_data[0][2] * m_data[3][3] +
                 m_data[1][1]  * m_data[0][3] * m_data[3][2] +
                 m_data[3][1] * m_data[0][2] * m_data[1][3] -
                 m_data[3][1] * m_data[0][3] * m_data[1][2];
     inv[1][2] = -m_data[0][0]  * m_data[1][2] * m_data[3][3] + //6
                  m_data[0][0]  * m_data[1][3] * m_data[3][2] +
                  m_data[1][0]  * m_data[0][2] * m_data[3][3] -
                  m_data[1][0]  * m_data[0][3] * m_data[3][2] -
                  m_data[3][0] * m_data[0][2] * m_data[1][3] +
                  m_data[3][0] * m_data[0][3] * m_data[1][2];
     inv[2][2] = m_data[0][0]  * m_data[1][1] * m_data[3][3] - //10
                 m_data[0][0]  * m_data[1][3] * m_data[3][1] -
                 m_data[1][0]  * m_data[0][1] * m_data[3][3] +
                 m_data[1][0]  * m_data[0][3] * m_data[3][1] +
                 m_data[3][0] * m_data[0][1] * m_data[1][3] -
                 m_data[3][0] * m_data[0][3] * m_data[1][1];
     inv[3][2] = -m_data[0][0]  * m_data[1][1] * m_data[3][2] + //14
                  m_data[0][0]  * m_data[1][2] * m_data[3][1] +
                  m_data[1][0]  * m_data[0][1] * m_data[3][2] -
                  m_data[1][0]  * m_data[0][2] * m_data[3][1] -
                  m_data[3][0] * m_data[0][1] * m_data[1][2] +
                  m_data[3][0] * m_data[0][2] * m_data[1][1];
     inv[0][3] = -m_data[0][1] * m_data[1][2] * m_data[2][3] + //3
                  m_data[0][1] * m_data[1][3] * m_data[2][2] +
                  m_data[1][1] * m_data[0][2] * m_data[2][3] -
                  m_data[1][1] * m_data[0][3] * m_data[2][2] -
                  m_data[2][1] * m_data[0][2] * m_data[1][3] +
                  m_data[2][1] * m_data[0][3] * m_data[1][2];
     inv[0][7] = m_data[0][0] * m_data[1][2] * m_data[2][3] - //7
                 m_data[0][0] * m_data[1][3] * m_data[2][2] -
                 m_data[1][0] * m_data[0][2] * m_data[2][3] +
                 m_data[1][0] * m_data[0][3] * m_data[2][2] +
                 m_data[2][0] * m_data[0][2] * m_data[1][3] -
                 m_data[2][0] * m_data[0][3] * m_data[1][2];
     inv[2][3] = -m_data[0][0] * m_data[1][1] * m_data[2][3] + //11
                  m_data[0][0] * m_data[1][3] * m_data[2][1] +
                  m_data[1][0] * m_data[0][1] * m_data[2][3] -
                  m_data[1][0] * m_data[0][3] * m_data[2][1] -
                  m_data[2][0] * m_data[0][1] * m_data[1][3] +
                  m_data[2][0] * m_data[0][3] * m_data[1][1];
     inv[3][3] = m_data[0][0] * m_data[1][1] * m_data[2][2] - //15
                 m_data[0][0] * m_data[1][2] * m_data[2][1] -
                 m_data[1][0] * m_data[0][1] * m_data[2][2] +
                 m_data[1][0] * m_data[0][2] * m_data[2][1] +
                 m_data[2][0] * m_data[0][1] * m_data[1][2] -
                 m_data[2][0] * m_data[0][2] * m_data[1][1];
     det=1.0/determinant();
     for(int i = 0; i<ROWS; i++)
     {
       for( int j = 0; j<COLS; j++)
       {
         tmp[i][j] = inv[i][j] * det;
       }
     }
   }
   for(int i = 0; i<ROWS; i++)
   {
     for( int j = 0; j<COLS; j++)
     {
       m_data[i][j]=tmp[i][j];
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> float Matrix< T, ROWS, COLS >::magnitude ()
Vector only methods.
Returns the magnitude of the given vector.
Definition at line 556 of file matrix.h.
 {
   vectorCheck();
   T sum = 0;
   float mag = 0;
   if(m_rows == 1)
   {
     for( int i = 0; i< COLS; i++)
     {
       sum += (m_data[0][i] * m_data[0][i]);
     }
   }
   if(m_cols == 1)
   {
     for( int i = 0; i< ROWS; i++)
     {
       sum += (m_data[i][0] * m_data[i][0]);
     }
   }
   mag= sqrt(sum);
   return mag;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::minorMatrix (int _row, int _col)
finds the minor matrix of a matrix param[in] _row, the row to be excluded from the original matrix in order to find the minor matrix param[in] _col, the column to be excluded from the original matrix in order to find the minor matrix
Definition at line 713 of file matrix.h.
 {
   // temporary matrix to store the minor matrices data
   T tmp[ROWS-1][COLS-1];
   // new matrix row index
   int k=0;
   // nex matrix column index
   int l=0;
   for(int i=0; i<ROWS-1; i++)
   {
     for(int j=0; j<COLS-1; j++)
     {
       tmp[i][j]=0;
     }
   }
   // row of minor matrix
   for(int i = 0; i<m_rows; i++)
   {
     if(i==_row-1)
     {
         i++;
     }
     // col of minor matrix
     for(int j = 0; j<m_cols; j++)
     {
       if(j==_col-1)
       {
         j++;
       }
       tmp[k][l]=m_data[i][j];
       l++;
     }
     // go back to first column
     l=0;
     k++;
   }
   // m_data row 1 disquilified so m-data row 2 equils tmp row 1
   for(int i=0; i<ROWS-1; i++)
   {
     for(int j=0; j<COLS-1; j++)
     {
       m_data[i][j]=tmp[i][j];
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::normalizeVector ()
Returns the normalized vector.
Definition at line 1230 of file matrix.h.
 {
   vectorCheck();
   T mag=magnitude();
   if(m_rows==1)
   {
     for(int i=0; i<m_cols; i++)
     {
       m_data[0][i]=m_data[0][i]/mag;
     }
   }
   if(m_cols==1)
   {
     for(int i=0; i<m_rows; i++)
     {
       m_data[i][0]=m_data[i][0]/mag;
     }
   }
     return *this;
 }
template<typename T , size_t ROWS, size_t COLS> T & Matrix< T, ROWS, COLS >::operator() (std::size_t _rowID, std::size_t _colID)
Subscript operator used to view values of matrix/vector based on row and column, starts at 1 not zero, eg first value is (1,1) param[in] _rowID, the row of the data you would like to access (1 for first row). param[in] _colID, the column of the data you would like to access (1 for first column).
Definition at line 506 of file matrix.h.
 {
   rangeCheck(_rowID,_colID);
   return m_data[_rowID-1][_colID-1];
 }
template<typename T , size_t ROWS, size_t COLS> const T & Matrix< T, ROWS, COLS >::operator() (std::size_t _rowID, std::size_t _colID) const
Subscript operator used to view values of matrix/vector based on row and column (read only) param[in] _rowID, the row of the data you would like to view (1 for first row). param[in] _colID, the column of the data you would like to view (1 for first column).
Definition at line 518 of file matrix.h.
 {
   rangeCheck(_rowID,_colID);
   return const_cast<T&>(m_data[_rowID-1][_colID-1]);
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator* (T _scalar)
Multiplication opertor for matrix/vector and _scalar param[in] _scalar, the value to multiple each value of m_data of the given matrix/vector by.
Definition at line 435 of file matrix.h.
 {
   for(int i=0; i<ROWS; i++)
   {
       for(int j=0; j<COLS; j++)
       {
         m_data[i][j]=m_data[i][j]*_scalar;
       }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> template<size_t N> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator* (Matrix< T, COLS, N > & _rhs)
Matrix only operations.
Multiplication operator for multiplying two matrices or vectors, the first matrix must have the same number of columns and the second has rows param[in] _rhs, the matrix/vector at the first matrix/vector is multiplied by For loop for multiplying vectors referenced from stackoverflow.com, accessed Jan 2017
Definition at line 372 of file matrix.h.
References Matrix< T, ROWS, COLS >::data(), Matrix< T, ROWS, COLS >::getCols(), and Matrix< T, ROWS, COLS >::getRows().
 {
   if( COLS!=_rhs.getRows())
   {
     throw std::out_of_range("number of columns of matrix 1 must be equil to number of rows of matrix 2");
   }
   // matrix-matrix multiplication
   if(m_vector == false)
   {
     // initialize tmp matrix values to 0
     T tmp[m_rows][_rhs.getCols()];
     for(int i=0; i<ROWS; i++)
     {
       for(int j=0; j<COLS; j++)
       {
         tmp[i][j]=0;
       }
     }
     // For loop structure referenced from http://stackoverflow.com/questions/10162467/matrix-multiplication-in-c
     // Multiplying matrices and storing values in matrix tmp
     for(int i = 0; i < m_rows; ++i)
     {
       for(int j = 0; j < _rhs.getCols(); ++j)
       {
         for(int k=0; k<m_cols; ++k)
         {
             tmp[i][j] += m_data[i][k] * _rhs.data(k,j);
         }
       }
     }
     // assignning the tmp matrix's values to m_data
     for(int i=0; i<m_rows; i++)
     {
       for(int j=0; j<m_cols; j++)
       {
         m_data[i][j]=tmp[i][j];
       }
     }
   }
   // vector vector multiplication
   else if (m_vector == true)
   {
     for(int i = 0; i < COLS; i++)
     {
         m_data[0][i]=m_data[0][i]*_rhs.data(0,i);
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator+ (const Matrix< T, ROWS, COLS > & _rhs)
Addition operator for matrix/vector and matrix/vector addition param[in] _rhs, the vector or matrix that is added to the first vector or matrix.
Definition at line 266 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_cols, Matrix< T, ROWS, COLS >::m_data, and Matrix< T, ROWS, COLS >::m_rows.
 {
   rangeCheck(_rhs.m_rows,_rhs.m_cols);
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       m_data[i][j]=m_data[i][j]+_rhs.m_data[i][j];
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator+ (T _scalar)
Addition operator for matrix/vector addition by a scalar amount param[in] _scalar, amount to add to each value of m_data for the given matrix/vector.
Definition at line 287 of file matrix.h.
 {
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       m_data[i][j]=m_data[i][j]+ _scalar;
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator- (const Matrix< T, ROWS, COLS > & _rhs)
Subtraction operator for matrix/vector and matrix/vector subtraction param[in] _rhs, the vector or matrix that is subtracted from the first vector or matrix.
Definition at line 307 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_cols, Matrix< T, ROWS, COLS >::m_data, and Matrix< T, ROWS, COLS >::m_rows.
 {
   rangeCheck(_rhs.m_rows,_rhs.m_cols);
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       m_data[i][j]=m_data[i][j]-_rhs.m_data[i][j];
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator- ()
Negative operator, returns each value of the matrix or vector with the opposite sign.
Definition at line 349 of file matrix.h.
 {
   //std::copy(_rhs.begin(),_rhs.end(), begin());
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       m_data[i][j]=-m_data[i][j];
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator- (T _scalar)
Subtraction operator for matrix/vector subtration by a scalar amount param[in] _scalar, amount to subtract from each value of m_data for the given matrix/vector.
Definition at line 329 of file matrix.h.
 {
   //std::copy(_rhs.begin(),_rhs.end(), begin());
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       m_data[i][j]=m_data[i][j]- _scalar;
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator/ (T _scalar)
Division operator for matrix/vector and _scalar param[in] _scalar, the value to divide each value of m_data of the given matrix/vector by.
Definition at line 454 of file matrix.h.
 {
   if(_scalar==0)
   {
     throw std::out_of_range("Cannot divide by 0");
   }
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       m_data[i][j]=m_data[i][j]/_scalar;
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator/ (Matrix< T, ROWS, COLS > & _rhs)
Division operator for vector and vector param[in] _rhs, the vector that the will be used to divide the other vector by.
Definition at line 528 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_data, and Matrix< T, ROWS, COLS >::vectorCheck().
 {
   vectorCheck();
   _rhs.vectorCheck();
   if(m_rows==1)
   {
    for(int i = 0; i< COLS; i++)
    {
      m_data[0][i]=m_data[0][i]/_rhs.m_data[0][i];
    }
   }
   else if(m_cols==1)
   {
    for(int i = 0; i< ROWS; i++)
    {
      m_data[i][0]=m_data[i][0]/_rhs.m_data[i][0];
    }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> template<size_t N, size_t M> Matrix< T, ROWS, COLS > Matrix< T, ROWS, COLS >::operator= (Matrix< T, N, M > & _rhs)
Matrix and Vector Operation.
Assignment operator for variable sized matrices, needed for matrix multiplication. param[in] _rhs, the matrix or vector that the first matrix or vector will be assigned too.
Definition at line 204 of file matrix.h.
References Matrix< T, ROWS, COLS >::data().
 {
   for(int i=0; i<m_rows; i++)
   {
     for(int j=0; j<m_cols; j++)
     {
       m_data[i][j]=_rhs.data(i,j);
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::operator= (const Matrix< T, ROWS, COLS > & _rhs)
Asignment Operator param[in] _rhs, the matrix or vector that the first matrix or vector will be assigned too.
Definition at line 223 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_cols, Matrix< T, ROWS, COLS >::m_data, and Matrix< T, ROWS, COLS >::m_rows.
 {
   rangeCheck(_rhs.m_rows,_rhs.m_cols);
   for(int i=0; i<ROWS; i++)
   {
     for(int j=0; j<COLS; j++)
     {
       m_data[i][j]=_rhs.m_data[i][j];
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> bool Matrix< T, ROWS, COLS >::operator== (const Matrix< T, ROWS, COLS > & _rhs)
Equility Operator, tests if vectors or matrices are equil and returns true if they are param[in] _rhs, the matrix or vector to test that the first vector or matrix equils.
Definition at line 243 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_data.
 {
   bool equil = true;
   for(int i = 0; i < m_rows; i ++)
   {
     for(int j = 0; j < m_cols; j ++)
     {
       if(m_data[i][j]!=_rhs.m_data[i][j])
       {
         equil= false;
       }
     }
   }
   return equil;
 }
template<typename T , size_t ROWS, size_t COLS> bool Matrix< T, ROWS, COLS >::orthogonal ()
Tests if the matrix is orthogonal (if the inversed matrix equils the transposed matrix)
Definition at line 1097 of file matrix.h.
 {
   bool orth = false;
   std::cout<<orth<<" orth \n";
   if(transpose() == inverse())
   {
     orth= true;
   }
   std::cout<<orth<<" orth \n";
   return orth;
 }
template<typename T , size_t ROWS, size_t COLS> void Matrix< T, ROWS, COLS >::print ()
Prints out the elements of the vector or matrix in the correct format.
Definition at line 1353 of file matrix.h.
 {
   for(int i = 0; i<m_rows; i++)
   {
     for(int j = 0; j<m_cols; j++)
     {
       std::cout<<m_data[i][j]<<" ";
     }
     // print space before starting next row
     std::cout<<"\n";
   }
   std::cout<<"\n";
 }
template<typename T , size_t ROWS, size_t COLS> void Matrix< T, ROWS, COLS >::rangeCheck (std::size_t rowID, std::size_t _colID) private
Checks rows and columns are in correct range, eg if you want the first row you would write 1 opposed to 0. param[in] _rowID, the row you would like to check is within 0 and the number of rows. param[in] _colID, the column you would like to check is within 0 and the number of columns.
Definition at line 480 of file matrix.h.
 {
   if( _rowID>ROWS || _rowID<1)
       throw std::out_of_range("row out of range");
   if( _colID>COLS || _colID<1)
       throw std::out_of_range("column out of range");
 }
template<typename T , size_t ROWS, size_t COLS> void Matrix< T, ROWS, COLS >::resize (int _rows, int _cols)
Resizes a matrix, resulting matrix must have the same number of elements as original matrix. param[in] _rows, the number of rows of the resulting matrix param[in] _cols, the number of columns of the resulting matrix.
Definition at line 1260 of file matrix.h.
 {
   if(ROWS*COLS != _rows*_cols)
   {
     throw std::out_of_range("Must resize to matrix with same number of elements, eg 2x3 to 3x2");
   }
   m_data[m_rows][m_cols]=m_data[_rows][_cols];
   m_rows=_rows;
   m_cols=_cols;
   for(int i = 0;i<m_rows;i++)
   {
     for(int j = 0;j< m_cols;j++)
     {
       m_data[i][j]=0;
     }
   }
 //    T tmp[m_cols][m_ros];
 //    for(int i = 0;i<m_rows;i++)
 //       {
 //           for(int j = 0;j< m_cols;j++)
 //           {
 //               tmp[i][j]=0;
 //           }
 //       }
 //    for(int i = 0;i<m_rows;i++)
 //       {
 //           for(int j = 0;j< m_cols;j++)
 //           {
 //               tmp[i][j]=m_data[i][j];
 //               std::cout<<tmp[i][j]<<" resize tmp \n";
 //           }
 //       }
     //std::cout<<m_data[2][0]<<"\n";
     //std::cout<<m_cols;
     //m_data[0][3]=0;
 //    for(int i = 0;i<m_rows;i++)
 //       {
 //           for(int j = 0;j< m_cols;j++)
 //           {
 //               m_data[i][j]=tmp[j][i];
 //               std::cout<<m_data[i][j]<<" resize new element \n";
 //           }
 //       }
 //    // initialize new column elements to zero
 //    for(int i = 0;i<m_rows;i++)
 //    {
 //        for(int j = m_cols;j< _cols;j++)
 //        {
 //            std::cout<<m_data[1][0]<<"\n";
 //            //std::cout<<i<<" "<<j<<"\n";
 //            //m_data[i][j]=0;
 //            std::cout<< i<<j<<" element "<<m_data[i][j]<<" new element \n";
 //        }
 //    }
 //    // initialize new row elements to zero
 //    for(int i = m_rows;i<_rows;i++)
 //    {
 //        for(int j = 0;j< _cols;j++)
 //        {
 //            //m_data[i][j]=0;
 //            std::cout<< i<<j<<" element "<<m_data[i][j]<<" new element \n";
 //        }
 //    }
 }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::rotateVector (T _angle, const char * _axis)
Rotates a 2d or 3d column vector by an angle counter clockwise around the selected axis (if 3d). param[in] _angle, the angle to rotate the vector by. param[in] _axis, the axis to rotate the vector around.
Definition at line 1121 of file matrix.h.
 {
   vectorCheck();
   if(m_cols!=1)
   {
     throw std::out_of_range("Must use a column vector for rotation eg Matrix<float,3,1>");
   }
   if(m_rows!= 2 && m_rows !=3)
   {
     throw std::out_of_range("Only 2D and 3D vectors are supported for rotation");
   }
   for(int i = 0; i < m_rows; i++)
   {
     for(int j; j< m_cols; j++)
     {
         //rotMat[i][j]=0;
     }
   }
   T tmp [m_rows];
   for(int i = 0 ;i<m_rows;i++)
   {
     tmp[i]=0;
   }
   //convert to radians
   double angle= _angle * (M_PI /180);
   // if 2d column vector use 2d rotation matrix
   if(m_rows==2)
   {
     T rotMat [m_rows][m_rows];
     // counter clockwise around the origin
     rotMat[0][0]=cos(angle);
     rotMat[0][1]= -sin(angle);
     rotMat[1][0]= sin(angle);
     rotMat[1][1]= cos(angle);
     for(int i = 0; i < 2; i ++)
     {
       for(int j = 0; j < 2; j++)
       {
           tmp[i]+=rotMat[i][j]*m_data[j][0];
       }
     }
   }
   // if 3d vector use 3d rotation matrix
   if(m_rows==3)
   {
     if(_axis == "x")
     {
       T rotMat [3][3]={1,0,0,0,cos(angle),-sin(angle),0,sin(-angle),cos(angle)};
       for(int i = 0; i < 3; i ++)
       {
         for(int j = 0; j < 3; j++)
         {
           tmp[i]+=rotMat[i][j]*m_data[j][0];
         }
       }
     }
     if(_axis == "y"){T rotMat [3][3]={cos(angle),0,sin(angle),0,1,0,-sin(angle),0,cos(-angle)};
       for(int i = 0; i < 3; i ++)
       {
         for(int j = 0; j < 3; j++)
         {
           tmp[i]+=rotMat[i][j]*m_data[j][0];
         }
       }
     }
     if(_axis == "z")
     {
       T rotMat [3][3]={cos(angle),-sin(angle),0,sin(angle),cos(angle),0,0,0,1};
       for(int i = 0; i < 3; i ++)
       {
         for(int j = 0; j < 3; j++)
         {
           tmp[i]+=rotMat[i][j]*m_data[j][0];
         }
       }
     }
   }
   for(int i = 0; i < m_rows; i ++)
   {
     m_data[i][0]=tmp[i];
   }
   return *this;
 }
template<typename T, size_t ROWS = 0, size_t COLS = 0> const int* Matrix< T, ROWS, COLS >::rows () const inline
Definition at line 54 of file matrix.h.
References Matrix< T, ROWS, COLS >::m_rows.
 { return m_rows; }
template<typename T , size_t ROWS, size_t COLS> Matrix< T, ROWS, COLS > & Matrix< T, ROWS, COLS >::transpose ()
returns the transpose version of a matrix
Definition at line 1059 of file matrix.h.
 {
   T tmp[COLS][ROWS];
   for(int i = 0;i<COLS;i++)
   {
     for(int j = 0;j< ROWS;j++)
     {
       tmp[i][j]=0;
     }
   }
   for(int i = 0; i< COLS; i++)
   {
     for(int j = 0; j < ROWS; j++)
     {
       tmp[i][j]= m_data[j][i];
     }
   }
   // resize matrix/vector to have reversed number of cols and rows
   resize(COLS,ROWS);
   for(int i = 0; i<m_rows; i++)
   {
     for( int j = 0; j<m_cols; j++)
     {
       m_data[i][j]=tmp[i][j];
     }
   }
   return *this;
 }
template<typename T , size_t ROWS, size_t COLS> void Matrix< T, ROWS, COLS >::vectorCheck () private
Checks that function is being applied to a matrix not a vector, throws error if it is a vector.
Definition at line 492 of file matrix.h.
 {
   if(m_rows !=1 && m_cols !=1)
   {
       throw std::out_of_range("You must use vectors only for this function");
   }
 }
Member Data Documentation
template<typename T, size_t ROWS = 0, size_t COLS = 0> int Matrix< T, ROWS, COLS >::m_cols =COLS private
Definition at line 27 of file matrix.h.
template<typename T, size_t ROWS = 0, size_t COLS = 0> T Matrix< T, ROWS, COLS >::m_data[ROWS][COLS] private
Definition at line 30 of file matrix.h.
template<typename T, size_t ROWS = 0, size_t COLS = 0> int Matrix< T, ROWS, COLS >::m_rows =ROWS private
Definition at line 24 of file matrix.h.
template<typename T, size_t ROWS = 0, size_t COLS = 0> bool Matrix< T, ROWS, COLS >::m_vector = false private
Definition at line 33 of file matrix.h.
The documentation for this class was generated from the following file:
matrix.h